export const ONE_STANDARD = '1 standard';
export const MAIN_ULR = 'https://swapi-trybe.herokuapp.com/api/';

export const mochResolved = {
  count: 60,
  next: 'https://swapi-trybe.herokuapp.com/api/planets/?page=2&format=json',
  previous: null,
  results: [
    {
      name: 'Tatooine',
      rotation_period: '23',
      orbital_period: '304',
      diameter: '10465',
      climate: 'arid',
      gravity: ONE_STANDARD,
      terrain: 'desert',
      surface_water: '1',
      population: '200000',
      residents: [
        MAIN_ULR.concat('people/1/'),
        MAIN_ULR.concat('people/2/'),
        MAIN_ULR.concat('people/4/'),
        MAIN_ULR.concat('people/6/'),
        MAIN_ULR.concat('people/7/'),
        MAIN_ULR.concat('people/8/'),
        MAIN_ULR.concat('people/9/'),
        MAIN_ULR.concat('people/11/'),
        MAIN_ULR.concat('people/43/'),
        MAIN_ULR.concat('people/62/'),
      ],
      films: [
        MAIN_ULR.concat('films/1/'),
        MAIN_ULR.concat('films/3/'),
        MAIN_ULR.concat('films/4/'),
        MAIN_ULR.concat('films/5/'),
        MAIN_ULR.concat('films/6/'),
      ],
      created: '2014-12-09T13:50:49.641000Z',
      edited: '2014-12-20T20:58:18.411000Z',
      url: MAIN_ULR.concat('planets/1/'),
    },
    {
      name: 'Alderaan',
      rotation_period: '24',
      orbital_period: '364',
      diameter: '12500',
      climate: 'temperate',
      gravity: ONE_STANDARD,
      terrain: 'grasslands, mountains',
      surface_water: '40',
      population: '2000000000',
      residents: [
        MAIN_ULR.concat('people/5/'),
        MAIN_ULR.concat('people/68/'),
        MAIN_ULR.concat('people/81/'),
      ],
      films: [
        MAIN_ULR.concat('films/1/'),
        MAIN_ULR.concat('films/6/'),
      ],
      created: '2014-12-10T11:35:48.479000Z',
      edited: '2014-12-20T20:58:18.420000Z',
      url: MAIN_ULR.concat('/planets/2/'),
    },
    {
      name: 'Yavin IV',
      rotation_period: '24',
      orbital_period: '4818',
      diameter: '10200',
      climate: 'temperate, tropical',
      gravity: ONE_STANDARD,
      terrain: 'jungle, rainforests',
      surface_water: '8',
      population: '1000',
      residents: [],
      films: [
        MAIN_ULR.concat('films/1/'),
      ],
      created: '2014-12-10T11:37:19.144000Z',
      edited: '2014-12-20T20:58:18.421000Z',
      url: MAIN_ULR.concat('planets/3/'),
    },
    {
      name: 'Hoth',
      rotation_period: '23',
      orbital_period: '549',
      diameter: '7200',
      climate: 'frozen',
      gravity: '1.1 standard',
      terrain: 'tundra, ice caves, mountain ranges',
      surface_water: '100',
      population: 'unknown',
      residents: [],
      films: [
        MAIN_ULR.concat('films/2/'),
      ],
      created: '2014-12-10T11:39:13.934000Z',
      edited: '2014-12-20T20:58:18.423000Z',
      url: MAIN_ULR.concat('planets/4/'),
    },
    {
      name: 'Dagobah',
      rotation_period: '23',
      orbital_period: '341',
      diameter: '8900',
      climate: 'murky',
      gravity: 'N/A',
      terrain: 'swamp, jungles',
      surface_water: '8',
      population: 'unknown',
      residents: [],
      films: [
        MAIN_ULR.concat('films/2/'),
        MAIN_ULR.concat('films/3/'),
        MAIN_ULR.concat('films/6/'),
      ],
      created: '2014-12-10T11:42:22.590000Z',
      edited: '2014-12-20T20:58:18.425000Z',
      url: MAIN_ULR.concat('planets/5/'),
    },
    {
      name: 'Bespin',
      rotation_period: '12',
      orbital_period: '5110',
      diameter: '118000',
      climate: 'temperate',
      gravity: '1.5 (surface), 1 standard (Cloud City)',
      terrain: 'gas giant',
      surface_water: '0',
      population: '6000000',
      residents: [
        MAIN_ULR.concat('people/26/'),
      ],
      films: [
        MAIN_ULR.concat('films/2/'),
      ],
      created: '2014-12-10T11:43:55.240000Z',
      edited: '2014-12-20T20:58:18.427000Z',
      url: MAIN_ULR.concat('planets/6/'),
    },
    {
      name: 'Endor',
      rotation_period: '18',
      orbital_period: '402',
      diameter: '4900',
      climate: 'temperate',
      gravity: '0.85 standard',
      terrain: 'forests, mountains, lakes',
      surface_water: '8',
      population: '30000000',
      residents: [
        MAIN_ULR.concat('people/30/'),
      ],
      films: [
        MAIN_ULR.concat('films/3/'),
      ],
      created: '2014-12-10T11:50:29.349000Z',
      edited: '2014-12-20T20:58:18.429000Z',
      url: MAIN_ULR.concat('planets/7/'),
    },
    {
      name: 'Naboo',
      rotation_period: '26',
      orbital_period: '312',
      diameter: '12120',
      climate: 'temperate',
      gravity: ONE_STANDARD,
      terrain: 'grassy hills, swamps, forests, mountains',
      surface_water: '12',
      population: '4500000000',
      residents: [
        MAIN_ULR.concat('people/3/'),
        MAIN_ULR.concat('people/21/'),
        MAIN_ULR.concat('people/35/'),
        MAIN_ULR.concat('people/36/'),
        MAIN_ULR.concat('people/37/'),
        MAIN_ULR.concat('people/38/'),
        MAIN_ULR.concat('people/39/'),
        MAIN_ULR.concat('people/42/'),
        MAIN_ULR.concat('people/60/'),
        MAIN_ULR.concat('people/61/'),
        MAIN_ULR.concat('people/66/'),
      ],
      films: [
        MAIN_ULR.concat('films/3/'),
        MAIN_ULR.concat('films/4/'),
        MAIN_ULR.concat('films/5/'),
        MAIN_ULR.concat('films/6/'),
      ],
      created: '2014-12-10T11:52:31.066000Z',
      edited: '2014-12-20T20:58:18.430000Z',
      url: MAIN_ULR.concat('planets/8/'),
    },
    {
      name: 'Coruscant',
      rotation_period: '24',
      orbital_period: '368',
      diameter: '12240',
      climate: 'temperate',
      gravity: ONE_STANDARD,
      terrain: 'cityscape, mountains',
      surface_water: 'unknown',
      population: '1000000000000',
      residents: [
        MAIN_ULR.concat('people/34/'),
        MAIN_ULR.concat('people/55/'),
        MAIN_ULR.concat('people/74/'),
      ],
      films: [
        MAIN_ULR.concat('films/3/'),
        MAIN_ULR.concat('films/4/'),
        MAIN_ULR.concat('films/5/'),
        MAIN_ULR.concat('films/6/'),
      ],
      created: '2014-12-10T11:54:13.921000Z',
      edited: '2014-12-20T20:58:18.432000Z',
      url: MAIN_ULR.concat('planets/9/'),
    },
    {
      name: 'Kamino',
      rotation_period: '27',
      orbital_period: '463',
      diameter: '19720',
      climate: 'temperate',
      gravity: ONE_STANDARD,
      terrain: 'ocean',
      surface_water: '100',
      population: '1000000000',
      residents: [
        MAIN_ULR.concat('people/22/'),
        MAIN_ULR.concat('people/72/'),
        MAIN_ULR.concat('people/73/'),
      ],
      films: [
        MAIN_ULR.concat('films/5/'),
      ],
      created: '2014-12-10T12:45:06.577000Z',
      edited: '2014-12-20T20:58:18.434000Z',
      url: MAIN_ULR.concat('planets/10/'),
    },
  ],
};
